apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sulsul
  namespace: argocd
spec:
  project: sulsul
  source:
    repoURL: "git@github.com:zeze1004/sulsul-gitOps.git"
    targetRevision: main
    path: ./sulsul-chart
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true