apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sulsul-be
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:depromeet/sulsul-BE"
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true