apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sulsul-be-repo
  namespace: argocd
spec:
  project: sulsul-cd
  source:
    repoURL: "git@github.com:depromeet/sulsul-BE"
    targetRevision: main
    path: .
  destination:
    server: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true