apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sulsul
  namespace: argocd
spec:
  project: sulsul
  source:
    repoURL: "git@github.com:depromeet/sulsul-BE"
    targetRevision: main
    path: .
  destination:
    name: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true