apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: sulsul
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: sulsul

---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80